### ISSUE TITLE
No debe aparecer

### ISSUE THREAD

**Issue by franlu** [Usama2004/1-DAM-Programacion#1]
https://github.com/Usama2004/1-DAM-Programacion/blob/aed45d5090f5ea31b0e633cdd2b66ed4c6b04a9c/02_EjerciciosT2/Ejercicio21.java#L14

En la línea 14 aparece un comentario por defecto que mete Netbeans. Borralo, y acostumbrate a borrarlo antes de subir un fichero al repositorio.

**Comment by Usama2004** [comment]
Hola profe, ya he hecho los cambios necesarios para que ya no me salga ni las licencias de java ni los comentarios por defecto
