### ISSUE TITLE
Aporta algo más de info

### ISSUE THREAD

**Issue by franlu** [Usama2004/1-DAM-Programacion#2]
https://github.com/Usama2004/1-DAM-Programacion/blob/aed45d5090f5ea31b0e633cdd2b66ed4c6b04a9c/02_EjerciciosT2/Ejercicio21.java#L28

Esta bien que indique que se ha producido un error, pero al usuario hay que darle algo más de información. Por ejemplo: " ERROR: y aquí describes el error que se ha producido."

**Comment by Usama2004** [comment]
Ya lo he corregido
